# This is a YAML file to install nginx onto oue web VM using YAML
---

  # where do we want to install
- hosts: web

# get the facts
  gather_facts: yes

# changes access to root user
  become: true

# what do we want ansible to do for us in the playbook
# In this case our only task is to install nginx


  tasks:
  - name: update apt-get
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  tasks:
  - name: upgrade all updates
    apt: upgrade=dist force_apt_get=yes

  tasks:
  - name: Install nginx
    apt: pkg=nginx state=present
    become_user: root

  - name: Remove nginx deafault file (delete file)
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    file:
      path: /etc/nginx/sites-enabled/reverseproxy.conf
      state: touch
      mode: '666'


  - name: Insert multiple lines and Backup
    blockinfile:
      path: /etc/nginx/sites-enabled/reverseproxy.conf
      block: |
        server{
          listen 80;
          server_name development.local;
          location / {
              proxy_pass http://127.0.0.1:3000;
          }
        }
  - name: Create a symbolic link
    file:
      src: /etc/nginx/sites-enabled/reverseproxy.conf
      dest: /etc/nginx/sites-available/reverseproxy.conf
      state: link

  - name: nginx bug workaround
    shell: |
      sudo mkdir /etc/systemd/system/nginx.service.d
        printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" | \
          sudo tee /etc/systemd/system/nginx.service.d/override.conf
      sudo systemctl daemon-reload
      sudo systemctl restart nginx


  - name: add apt key for node source
    apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

  - name: add repo for nodesource
    apt_repository:
          repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
          update_cache: yes

  - name: install node js
    apt: name=nodejs

#  - name: trying stuff
#    apt: pkg=npm state=present

 # Downloading pm2
#  - name: Install pm2
#    npm:
#      name: pm2
#      global: yes

  - name: download latest npm
    shell: |
      npm install -g npm@latest
      npm install mongoose -y


  - name: set up app
    shell: |
      cd app/
      npm install
      node seeds/seed.js
      #pm2 kill
      #pm2 start app.js
       node app.js
    environment:
      DB_HOST: mongodb://18.203.172.245:27017/posts?authSource=admin
    become_user: root
